Repository keboola/storage-api-php-client, pull requests merged in 2022-06, with the labels that each got.

#822 CreateWorkspace async
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
  tests/Backend/Workspaces/WorkspacesTest.php
  tests/Common/BranchWorkspacesTest.php
Labels: minor

#825 Make workspace drop/create sync by default
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Exasol/Workspace/WorkspaceLoadTest.php
  tests/Backend/FileWorkspace/FileWorkspaceTestCase.php
  tests/Backend/FileWorkspace/WorkspacesTest.php
  tests/Backend/Mixed/LegacyWorkspacesTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php
  tests/Backend/Mixed/Workspaces/S3WorkspacesTest.php
  tests/Backend/Mixed/WorkspacesRenameTest.php
  tests/Backend/MixedSnowflakeExasol/SharingTest.php
  tests/Backend/MixedSnowflakeSynapse/SharingTest.php
  tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
  tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
  tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
  tests/Backend/Workspaces/ReadOnlyUserTest.php
  tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
  tests/Backend/Workspaces/WorkspacesExasolTest.php
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
  tests/Backend/Workspaces/WorkspacesSynapseTest.php
  tests/Backend/Workspaces/WorkspacesTest.php
  tests/Backend/Workspaces/WorkspacesTestCase.php
Labels: no release

#824 KBC-2691 Validate event JSON schema in Create Event endpoint
  tests/Common/EventsTest.php
Labels: no release

#831 KBC-2627 api doc: add correct request for bucket update
  apiary.apib
Labels: patch

#829 fix testBucketCreateWithoutDescription
  tests/Backend/CommonPart1/BucketsTest.php
Labels: no release
