Repository keboola/storage-api-php-client, pull requests merged in 2022-07, with the labels that each got.

#827 KBC-2747 add registerBucket method
  apiary.apib
  phpstan-baseline.neon
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/CommonPart1/RegisterBucketTest.php
  tests/Backend/Exasol/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
  tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
  tests/Backend/Synapse/CreateTableTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
  tests/Backend/Workspaces/Backend/ExasolWorkspaceBackend.php
  tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php
  tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php
  tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php
  tests/Backend/Workspaces/Backend/TeradataWorkspaceBackend.php
  tests/Backend/Workspaces/Backend/WorkspaceBackend.php
  tests/Backend/Workspaces/WorkspacesLoadTest.php
  tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
Labels: minor

#837 KBC-2781 RegisterBucketTest tests events
  tests/Backend/CommonPart1/RegisterBucketTest.php
Labels: no release

#838 KBC-2716 update deps and latest phpstan
  composer.json
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
Labels: no release

#839 Roman gsc 2735 sliced
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/GCSUploader.php
Labels: minor

#840 KBC-2714 it should not be possible to rename the main branch
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/DevBranches.php
  tests/Common/DevBranchesTest.php
Labels: patch

#844 Test for CSV with columns-data missmatch
  tests/Backend/CommonPart1/CreateTableTest.php
Labels: no release

#847 skip synapse only
  tests/Backend/CommonPart1/CreateTableTest.php
Labels: no release

#842 Add GcsDownloader
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Downloader/DownloaderFactory.php
  src/Keboola/StorageApi/Downloader/GcsClientFactory.php
  src/Keboola/StorageApi/Downloader/GcsDownloader.php
Labels: minor

#846 Add backend snowflake gcs test
  apiary.apib
  phpunit.xml.dist
  src/Keboola/StorageApi/GCSUploader.php
  tests/Backend/CommonPart2/SlicedImportsTest.php
  tests/Backend/Export/ExportParamsTest.php
  tests/Backend/Export/ExportSimpleTest.php
  tests/StorageApiTestCase.php
Labels: minor
