Repository keboola/storage-api-php-client, pull requests merged in 2022-09, with the labels that each got.

#852 Kbc 2718 app err when linked bucket already exist
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
Labels: no release

#875 KBC-2791 KBC-2893 KBC-2870 update expected Snowflake metadata
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
Labels: no release

#872 KBC-2814 add CreateTokenRequest and CreateLimitedTokenRequest
  tests/Common/TokensTest.php
Labels: no release

#876 KBC-2815 update apiary documentation - add get trigger
  apiary.apib
Labels: no release

#874 KBC-2815 replace CreateTriggerRequest
  tests/Common/TriggersTest.php
Labels: no release

#885 KBC-2909 createLimitedToken: expiresIn as optional
  apiary.apib
Labels: no release

#894 KBC-2909 createLimitedToken: expiresIn as optional - fix tests
  tests/Common/TokensTest.php
Labels: no release

#879 KBC-2761 improve base methods that sends requests
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
Labels: patch

#889 KBC-2761 migrate Tickets to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Common/ComponentsEventsTest.php
Labels: patch

#890 KBC-2761 migrate Triggers to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
Labels: patch

#895 KBC-2761 migrate Tickets to JSON - fix type hint
  src/Keboola/StorageApi/Client.php
  tests/Common/ComponentsEventsTest.php
Labels: no release

#878 KBC-2761 tokens use json
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/TokenAbstractOptions.php
  src/Keboola/StorageApi/Options/TokenCreateOptions.php
  src/Keboola/StorageApi/Tokens.php
  tests/Common/TokensTest.php
Labels: patch

#887 KBC-2761 migrate Metadata to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Metadata.php
  tests/Common/MetadataTest.php
Labels: patch

#886 KBC-2761 migrate Events to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Event.php
  tests/Common/BranchEventsTest.php
  tests/Common/EventsTest.php
  tests/StorageApiTestCase.php
Labels: patch

#881 KBC-2761 migrate Tables to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
Labels: patch

#893 KBC-2761 migrate Components to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Components.php
  tests/Common/ComponentsTest.php
  tests/Common/ConfigurationRowTest.php
Labels: patch

#891 KBC-2761 migrate DevBranches to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/DevBranches.php
Labels: minor

#896 KBC-2866 skip maintenance url page
  tests/Common/MaintenanceTest.php
Labels: no release

#899 Test stack ID existence in storage index
  tests/Common/IndexTest.php
Labels: minor
