Repository keboola/storage-api-php-client, pull requests merged in 2022-08, with the labels that each got.

#850 remov getDuplicityAction test
  phpstan-baseline.neon
  tests/Backend/Redshift/DedupeTest.php
Labels: no release

#843 KBC-2792 enable create snapshot on typed table test
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#855 composer: keboola/coding-standard moved to require-dev
  composer.json
Labels: patch

#858 GCSUploader - simplify sliced file manifest upload
  src/Keboola/StorageApi/GCSUploader.php
Labels: patch

#857 remove LegacyIndexedColumnsTest
  tests/Backend/CommonPart1/LegacyIndexedColumnsTest.php
Labels: no release

#853 KBC-2828 add snowflake add column on typed tables
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: minor

#859 KBC-2850 add testCreateTableWithPrimaryKeyBasetype
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#856 Kbc 2813 remove bucket attribute
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/BucketsTest.php
Labels: major

#860 KBC-2830 testCreateTableWithPrimaryKeyBasetype -> testPrimaryKeys
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#861 Roman fix slicing uploads handle promise and retry
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/GCSUploader.php
  src/Keboola/StorageApi/GCSUploader/PromiseHandler.php
  tests/GCSUploader/PromiseHandlerTest.php
Labels: patch

#865 KBC-2841 storage api client configuration row strict types
  phpstan-baseline.neon
  tests/Common/ComponentsTest.php
  tests/Utils/ComponentsConfigurationUtils.php
Labels: no release

#864 Kbc 2862 user error when load fails to native types
  tests/Backend/Snowflake/ImportTypedTableTest.php
Labels: no release

#854 KBC-2790 fix ro on endpoints storage buckets controller
  apiary.apib
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/Snowflake/TimeTravelTest.php
  tests/Common/QueueJobsTest.php
Labels: no release

#868 ImportTypedTableTest ignore when feature is not set
  tests/Backend/Snowflake/ImportTypedTableTest.php
Labels: no release

#869 fix async call of dropBucketIfExists
  tests/Backend/CommonPart1/RegisterBucketTest.php
Labels: no release

#870 KBC-2794 test failing OM on type mismatch
  tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Labels: no release
