Repository keboola/storage-api-php-client, pull requests merged in 2022-10, with the labels that each got.

#902 Fix event checks in tests
  tests/StorageApiTestCase.php
  tests/Utils/EventTesterUtils.php
  tests/Utils/EventTesterUtilsImpl.php
  tests/Utils/EventTesterUtilsTest.php
Labels: no release

#897 KBC-2921 add buckets/tables-with-configuration
  apiary.apib
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/TableWithConfigurationOptions.php
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Utils/EventTesterUtils.php
Labels: minor

#904 KBC-2919 execute custom query (migration
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
Labels: minor

#905 KBC-2933 Refactoring tests
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
  tests/Backend/TableWithConfigurationUtils.php
  tests/StorageApiTestCase.php
Labels: no release

#907 add new bq test suite
  phpunit.xml.dist
  tests/Backend/CommonPart1/BucketsTest.php
  tests/StorageApiTestCase.php
Labels: no release

#871 KBC-2713 test numeric column names
  apiary.apib
  src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php
  tests/Common/MetadataTest.php
Labels: no release

#911 add assert to metadata test
  tests/Common/MetadataTest.php
  tests/File/CommonFileTest.php
Labels: no release

#910 Update test and docs (128px icon)
  apiary.apib
  tests/Common/IndexTest.php
  tests/File/CommonFileTest.php
Labels: minor

#908 remove Google ApiClient
  composer.json
Labels: no release

#914 KBC-3000 test table with configuration response
  apiary.apib
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
Labels: patch
