Repository keboola/storage-api-php-client, pull requests merged in 2023-02, with the labels that each got.

#989 CT-789 move config under parameters
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
  tests/Backend/TableWithConfigurationUtils.php
Labels: no release

#993 CT-789 nest config under parameters
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
Labels: no release

#977 Split TD suites
  phpunit.xml.dist
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart2/SimpleAliasTest.php
Labels: no release

#995 CT-832 fix test expectation
  tests/Common/StatsTest.php
Labels: no release

#996 Use new event tests
  tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
Labels: no release

#1000 Fix build
  Dockerfile
Labels: no release

#999 CT-784 test numeric column names
  apiary.apib
  src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php
  tests/Common/MetadataTest.php
Labels: no release

#997 Ter 103 external bucket drop role
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
  tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
Labels: no release

#998 TER-89 columns limit
  phpstan-baseline.neon
  phpunit.xml.dist
  tests/Backend/CommonPart1/AlterTableTest.php
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart2/TablesDefinitionCommonTest.php
Labels: no release

#1002 CT-866 run export tests with para buckets
  phpunit.xml.dist
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/CommonPart1/TableExporterTest.php
  tests/Backend/Export/ExportParamsTest.php
  tests/Backend/Export/ExportSimpleTest.php
  tests/Backend/Export/SnapshotSimpleTest.php
  tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
Labels: no release

#954 KBC-2941 update table uses JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
Labels: patch

#957 CT-856 update table filter use JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart2/SimpleAliasTest.php
  tests/Common/SearchComponentsConfigurationsTest.php
Labels: patch

#1005 CT-863 create snapshot uses JSON
  src/Keboola/StorageApi/Client.php
Labels: patch

#1003 CT-858 udpate table delete rows use JSON
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: patch

#1004 CT-876 json create table alias
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
Labels: patch

#880 CT-885 migrate Buckets to JSON
  src/Keboola/StorageApi/Client.php
  tests/Backend/Mixed/SharingTest.php
Labels: patch

#883 CT-884 migrate Workspaces to JSON
  phpstan-baseline.neon
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/FileWorkspace/WorkspacesUnloadTest.php
  tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
Labels: minor
