Repository keboola/storage-api-php-client, pull requests merged in 2023-04, with the labels that each got.

#1035 test sync linked tables display name
  tests/Backend/Mixed/SharingTest.php
Labels: no release

#1039 uncomment retry
  tests/ClientTestCase.php
Labels: no release

#1030 CT-342 create config from version fails
  apiary.apib
  tests/Common/ComponentsTest.php
Labels: no release

#1037 fix listJobsByRunId returns array
  phpstan-baseline.neon
  tests/Backend/CommonPart1/TableExporterTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1034 Ct 943 move bq to own dir
  phpunit.xml.dist
  tests/Backend/Bigquery/TableExporterTest.php
Labels: no release

#1025 CT-549 delete tables attributes
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/CommonPart2/SnapshottingTest.php
  tests/Common/TablesListingTest.php
  tests/Common/TokensTest.php
Labels: major

#1028 CT-550 delete deprecated indexedColumns
  apiary.apib
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/Synapse/CreateTableTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
Labels: no release

#1036 apiPost => apiPostJson
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart2/MetricsTest.php
  tests/Backend/Redshift/OptimizeTest.php
  tests/Backend/Snowflake/TableExportTest.php
  tests/Backend/Snowflake/TimestampTest.php
  tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
  tests/Backend/Workspaces/ExasolWorkspacesUnloadTest.php
  tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php
  tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
  tests/Backend/Workspaces/WorkspacesUnloadTest.php
  tests/Common/MetadataTest.php
Labels: no release

#1044 CT-984 test missing values in data-preview
  tests/Backend/CommonPart1/DataPreviewLimitsTest.php
Labels: no release

#1045 test add column basetype on Exasol and Synapse
  apiary.apib
  tests/Backend/Exasol/TableDefinitionOperationsTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
Labels: patch

#1046 CT-666 test deduplication behavior of typed tables
  tests/Backend/Snowflake/ImportTypedTableTest.php
  tests/_data/languages.more-rows_without_zero.csv
Labels: no release

#1047 CT-971 return definition
  apiary.apib
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Exasol/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
Labels: patch

#1048 Init test type exceptions handling
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release
