Repository keboola/storage-api-php-client, pull requests merged in 2023-07, with the labels that each got.

#1096 Sox 2 merge endpoint
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Common/BranchComponentTest.php
  tests/Common/ClientProviderTest.php
  tests/Common/ComponentsTest.php
  tests/Common/ConfigurationMetadataTest.php
  tests/Common/SearchComponentsConfigurationsTest.php
  tests/StorageApiTestCase.php
Labels: minor

#1108 fix baseline
  phpstan-baseline.neon
Labels: no release

#1106 SOX-153 tokens hide
  phpunit.xml.dist
  tests/Backend/SOX/SOXTokensTest.php
Labels: no release

#1104 Sox 2merge job part 3
  phpstan-baseline.neon
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1107 SOX fix mr tests
  phpunit.xml.dist
  src/Keboola/StorageApi/DevBranches.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1109 SOX-117 SOX-123 reject->request-changes, branch locking
  apiary.apib
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
Labels: minor

#1111 test branch is deleted after merge
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1110 Start test metadata
  phpstan-baseline.neon
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1113 test branch is deleted after merge
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1116 SOX-165 add branch id to ws load
  apiary.apib
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Labels: minor

#1121 Jirka fix sox suite
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1115 SOX-21 table pull
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/PullTableTest.php
Labels: minor

#1123 fix pull docs
  apiary.apib
Labels: no release

#1117 SOX-201 Branch table jobs
  tests/Backend/SOX/BranchStorageTest.php
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1120 Move getBranchesForCurrentTestCase to base test case
  tests/Backend/SOX/BranchStorageTest.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Backend/SOX/PullTableTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1118 test branch file export
  tests/Backend/SOX/ExportTableTest.php
Labels: no release

#1124 Sox 20 table export in branch backoff
  apiary.apib
  src/Keboola/StorageApi/BranchAwareClient.php
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/TableExporter.php
  tests/Backend/SOX/ExportTableTest.php
Labels: minor

#1127 fix sox suite
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Backend/SOX/PullTableTest.php
Labels: no release

#1128 fix two more branch delete usecases
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1125 SOX-200 test listing in branch storage
  tests/Backend/SOX/BranchStorageTest.php
Labels: no release

#1126 SOX-213 add canCreateJobs test
  tests/Common/TokensTest.php
Labels: no release

#1129 Sox 208 improve tests
  tests/Backend/SOX/BranchStorageTest.php
  tests/Backend/SOX/ExportTableTest.php
  tests/Backend/SOX/SOXCommonTest.php
Labels: no release

#1130 SOX-17 add events to MR test
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1131 SOX-17 part2: add create mr event test
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1132 fix expected error messages
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Common/DevBranchesTest.php
Labels: no release

#1135 Test self-approval
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1134 SOX-121 Create list of changed things when MR put to review
  apiary.apib
  tests/Backend/SOX/MergeRequestsTest.php
Labels: patch

#1136 SOX-194 BranchStorageTest test events fired
  tests/Backend/SOX/BranchStorageTest.php
Labels: no release

#1078 SOX-66 buckets branched storage
  phpstan-baseline.neon
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/BucketsTest.php
  tests/ClientProvider/ClientProvider.php
  tests/ClientProvider/TestSetupHelper.php
  tests/Common/BranchEventsTest.php
  tests/Common/MetadataTest.php
  tests/Common/SearchTablesTest.php
  tests/Common/TablesListingTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1138 SOX-294 test CRUD triggers in SOX
  tests/Backend/SOX/TriggersTest.php
Labels: no release

#1140 SOX-163 test testCanCreateBucket in dev branch
  tests/Backend/CommonPart1/BranchStorageTest.php
Labels: no release

#1141 SOX-288 mr cancel
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1142 SOX-289 drop cancelMergeRequest
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
Labels: major, minor, patch

#1144 SOX-84 test testCreateTriggerInBranch
  tests/Backend/SOX/TriggersTest.php
Labels: no release

#1149 SOX-321 add TableEventsTest
  tests/Common/TableEventsTest.php
Labels: no release

#1148 test delete files in branch after branch deleted
  tests/Backend/SOX/BranchFileStorageTest.php
Labels: no release

#1146 SOX-290 assert new merge conflict errors
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1150 SOX-86 e2e branches
  phpunit.xml.dist
  tests/Backend/SOX/BranchFileStorageTest.php
  tests/Backend/SOX/BranchStorageTest.php
  tests/Backend/SOX/ExportTableTest.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Backend/SOX/PullTableTest.php
  tests/Backend/SOX/SOXBranchesTest.php
  tests/Backend/SOX/TriggersTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1143 Sox 24 test files branch aware
  phpstan-baseline.neon
  phpunit.xml.dist
  tests/File/AwsFileTest.php
  tests/File/CommonFilePermissionsTest.php
  tests/File/CommonFileTest.php
  tests/StorageApiTestCase.php
Labels: no release

#1147 SOX-271 (4) Test snapshot endpoint
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/BranchStorageTest.php
Labels: no release
