Repository keboola/storage-api-php-client, pull requests merged in 2023-01, with the labels that each got.

#961 BQ test alter table
  apiary.apib
  phpunit.xml.dist
  tests/Backend/CommonPart1/AlterTableTest.php
Labels: no release

#962 enable more typed table tests for BQ
  phpunit.xml.dist
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/CommonPart1/DataPreviewLimitsTest.php
Labels: no release

#966 Kbc 3081 async ws configuration create
  apiary.apib
  src/Keboola/StorageApi/Components.php
  tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
  tests/Backend/Workspaces/ComponentsWorkspacesTest.php
Labels: minor

#967 TER-53 skip ws load and enable tests
  apiary.apib
  tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
  tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
Labels: no release

#964 Enable PK tests for TD and BQ
  phpstan-baseline.neon
  tests/Backend/CommonPart1/AlterTableTest.php
Labels: no release

#971 Fix BQ testFindDataByFulltext
  tests/Backend/Bigquery/FulltextSearchTest.php
Labels: no release

#969 Big 35 import from time travel
  apiary.apib
  phpstan-baseline.neon
  phpunit.xml.dist
  tests/Backend/CommonPart1/TimeTravelTest.php
Labels: no release

#968 TER-87 delete rows - supports whereFilters
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: minor

#970 BIG-105 delete rows
  phpunit.xml.dist
  tests/Backend/CommonPart2/SlicedImportsTest.php
  tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
Labels: no release

#973 doc - add supported datatypes for export and data preview
  apiary.apib
Labels: no release

#972 TER-87 delete rows - multiple whereFilters
  phpstan-baseline.neon
  phpunit.xml.dist
  tests/Backend/CommonPart1/DeleteRowsTest.php
  tests/Backend/CommonPart2/SlicedImportsTest.php
  tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
Labels: no release

#978 Fix: Table rows delete: split call with query and form-data
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: patch

#975 Test delete not sliced prepared file
  tests/File/GcsFileTest.php
Labels: no release

#976 CT-781 Fix booleanish validator usage for RO role
  tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
  tests/Backend/Workspaces/ComponentsWorkspacesTest.php
Labels: no release

#980 CT-781 only test RO storage access on snowflake backends
  tests/Backend/Workspaces/ComponentsWorkspacesTest.php
Labels: no release

#983 Update PR template CT and link to KBC
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no release

#984 CT-774 add HTTP headers to Apiary
  apiary.apib
Labels: no release

#979 Make event assertions robust
  phpstan-baseline.neon
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/RegisterBucketTest.php
  tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
  tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
  tests/Backend/FileWorkspace/WorkspacesTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/MixedSnowflakeExasol/SharingTest.php
  tests/Backend/MixedSnowflakeSynapse/SharingTest.php
  tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
  tests/Backend/Synapse/CreateTableTest.php
  tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
  tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
  tests/Backend/Workspaces/WorkspacesTest.php
  tests/Common/BranchEventsTest.php
  tests/Common/BranchMetadataTest.php
  tests/Common/BranchWorkspacesTest.php
  tests/Common/ComponentsEventsTest.php
  tests/Common/ComponentsTest.php
  tests/Common/ConfigurationMetadataTest.php
  tests/Common/DevBranchesTest.php
  tests/Common/EventsAttachmentTest.php
  tests/Common/EventsTest.php
  tests/Common/SearchComponentsConfigurationsTest.php
  tests/Common/TokensShareTest.php
  tests/Utils/EventTesterUtils.php
  tests/Utils/EventsQueryBuilder.php
  tests/Utils/EventsQueryBuilderTest.php
Labels: no release

#982 CT-786 update assertions for Invalid request message
  tests/Backend/Synapse/CreateTableTest.php
  tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
  tests/Common/ComponentsTest.php
  tests/Common/SearchTablesTest.php
Labels: no release

#985 Update version in Client
  src/Keboola/StorageApi/Client.php
Labels: no release

#981 TER-99 external buckets for TD
  apiary.apib
  phpunit.xml.dist
  tests/Backend/ExternalBuckets/BaseExternalBuckets.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
  tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
  tests/StorageApiTestCase.php
Labels: no release

#987 Fix events for snflk ext buckets
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart2/SnapshottingTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#986 deprecate sync actions, use maximal async actions
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/Bigquery/FulltextSearchTest.php
  tests/Backend/Bigquery/OrderByTest.php
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Bigquery/WhereFilterTest.php
  tests/Backend/CommonPart1/AlterTableTest.php
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart1/DataPreviewLimitsTest.php
  tests/Backend/CommonPart1/DeleteRowsTest.php
  tests/Backend/CommonPart1/DeleteTableTest.php
  tests/Backend/CommonPart1/ExportParamsTest.php
  tests/Backend/CommonPart1/ImportExportCommonTest.php
  tests/Backend/CommonPart1/TableExporterTest.php
  tests/Backend/CommonPart1/TimeTravelTest.php
  tests/Backend/CommonPart2/SimpleAliasTest.php
  tests/Backend/CommonPart2/SlicedImportsTest.php
  tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
  tests/Backend/CommonPart2/SystemColumnsTest.php
  tests/Backend/Exasol/OrderByTest.php
  tests/Backend/Exasol/TableDefinitionOperationsTest.php
  tests/Backend/Exasol/WhereFilterTest.php
  tests/Backend/Mixed/LegacyWorkspacesTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/WorkspacesRenameTest.php
  tests/Backend/Redshift/CommonTest.php
  tests/Backend/Redshift/CreateTableTest.php
  tests/Backend/Redshift/OptimizeTest.php
  tests/Backend/Redshift/OrderByTest.php
  tests/Backend/Redshift/WhereFilterTest.php
  tests/Backend/Snowflake/FulltextSearchTest.php
  tests/Backend/Snowflake/OrderByTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TimestampTest.php
  tests/Backend/Synapse/FulltextSearchTest.php
  tests/Backend/Synapse/OrderByTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
  tests/Backend/Teradata/FulltextSearchTest.php
  tests/Backend/Teradata/OrderByTest.php
  tests/Backend/Teradata/TableDefinitionOperationsTest.php
  tests/Backend/Teradata/WhereFilterTest.php
  tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
  tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
  tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
  tests/Backend/Workspaces/WorkspacesExasolTest.php
  tests/Backend/Workspaces/WorkspacesLoadTest.php
  tests/Backend/Workspaces/WorkspacesRedshiftTest.php
  tests/Backend/Workspaces/WorkspacesRenameLoadTest.php
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
  tests/Backend/Workspaces/WorkspacesSynapseTest.php
  tests/Backend/Workspaces/WorkspacesUnloadTest.php
  tests/Common/BranchBucketsTest.php
  tests/Common/EventsAttachmentTest.php
  tests/Common/SearchTablesTest.php
  tests/Common/StatsTest.php
  tests/Common/TablesListingTest.php
  tests/Common/TokensTest.php
  tests/StorageApiTestCase.php
Labels: no release

#990 Use create table async
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/AlterTableTest.php
  tests/Backend/CommonPart1/ImportExportCommonTest.php
  tests/Backend/CommonPart1/TimeTravelTest.php
  tests/Backend/CommonPart2/MetricsTest.php
  tests/Backend/CommonPart2/SimpleAliasTest.php
  tests/Backend/CommonPart2/SnapshottingTest.php
  tests/Backend/CommonPart2/SystemColumnsTest.php
  tests/Backend/Exasol/Workspace/WorkspaceLoadTest.php
  tests/Backend/FileWorkspace/WorkspacesLoadTest.php
  tests/Backend/Mixed/LegacyWorkspacesTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php
  tests/Backend/Mixed/Workspaces/S3WorkspacesTest.php
  tests/Backend/MixedSnowflakeExasol/SharingTest.php
  tests/Backend/MixedSnowflakeSynapse/SharingTest.php
  tests/Backend/Redshift/ImportExportCommonTest.php
  tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
  tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
  tests/Backend/Snowflake/WhereFilterTest.php
  tests/Backend/Synapse/WhereFilterTest.php
  tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
  tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
  tests/Backend/Workspaces/LegacyWorkspacesExasolTest.php
  tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
  tests/Backend/Workspaces/LegacyWorkspacesRedshiftTest.php
  tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php
  tests/Backend/Workspaces/LegacyWorkspacesSynapseTest.php
  tests/Backend/Workspaces/MetadataFromExasolWorkspaceTest.php
  tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php
  tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php
  tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
  tests/Backend/Workspaces/WorkspacesExasolTest.php
  tests/Backend/Workspaces/WorkspacesLoadTest.php
  tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
  tests/Backend/Workspaces/WorkspacesRedshiftTest.php
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
  tests/Backend/Workspaces/WorkspacesSynapseTest.php
  tests/Common/MetadataTest.php
  tests/Common/StatsTest.php
  tests/Common/TablesListingTest.php
  tests/Common/TokensTest.php
Labels: no release

#991 Download files - handle not found errors from cloud providers
  src/Keboola/StorageApi/Client.php
  tests/File/CommonFileTest.php
Labels: patch
