Repository keboola/storage-api-php-client, pull requests merged in 2023-06, with the labels that each got.

#1066 CT-1055 CT-1044 Update IE lib snflk exceptions
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Labels: no release

#1060 CT-910 register external table
  apiary.apib
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: patch

#1067 CT-1086 test dropping
  apiary.apib
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1063 CT-911 test view registration
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1064 CT-1003 snflk exotic types filtering
  apiary.apib
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#1070 CT-1003 update tests to expect canBeFiltered
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Exasol/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Synapse/TableDefinitionOperationsTest.php
Labels: no release

#1065 CT-991 generate queries for grants
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: minor

#1069 CT-1031 test data preview filters for snowflake
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#1075 SOX-28 Fix error messages related to access to resources
  tests/Backend/Workspaces/ReadOnlyUserTest.php
  tests/Common/ComponentsTest.php
  tests/Common/ConfigurationMetadataTest.php
  tests/Common/TriggersTest.php
  tests/File/CommonFileTest.php
Labels: no release

#1071 Make guide endpoint GET
  apiary.apib
Labels: no release

#1072 SOX-1 add method to create privileged token
  apiary.apib
  docker-compose.yml
  phpstan.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/TokenCreateOptions.php
  src/Keboola/StorageApi/Tokens.php
  tests/Common/TokensTest.php
  tests/bootstrap.php
Labels: minor

#1077 SOX-18 SNFLK view load
  apiary.apib
  phpstan-baseline.neon
  tests/Backend/WorkspaceConnectionTrait.php
  tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackendDBAL.php
  tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php
  tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Labels: no release

#1080 SOX-13 create MR
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Common/MergeRequestsTest.php
Labels: minor

#1073 Test version unique identifikator
  apiary.apib
  tests/Common/BranchComponentTest.php
  tests/Common/ComponentsTest.php
Labels: no release

#1079 SOX-40 Test branch behavior for non-admin token
  tests/Common/DevBranchesTest.php
Labels: minor

#1084 SOX-13 MR detail
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Common/MergeRequestsTest.php
Labels: minor

#1081 SOX-73 init suite
  docker-compose.yml
  phpunit.xml.dist
  tests/Backend/SOX/SOXCommonTest.php
  tests/ClientTestCase.php
  tests/bootstrap.php
Labels: no release

#1085 SOX-78 tokens
  apiary.apib
  phpunit.xml.dist
  tests/Backend/SOX/SOXCommonTest.php
  tests/Backend/SOX/SOXTokensTest.php
Labels: no release

#1091 SOX-14 init tests for wf
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/ClientTestCase.php
Labels: minor

#1093 SOX-14 add new states
  apiary.apib
  docker-compose.yml
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/ClientTestCase.php
  tests/bootstrap.php
Labels: minor

#1099 SOX-13 list MRs
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1095 SOX-84 canCreateJobs
  apiary.apib
  docker-compose.yml
  phpstan.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/TokenCreateOptions.php
  src/Keboola/StorageApi/Tokens.php
  tests/Backend/SOX/SOXTokensTest.php
  tests/bootstrap.php
Labels: minor

#1097 enable testing versionIdentifier
  tests/Common/BranchComponentTest.php
  tests/Common/ComponentsTest.php
Labels: no release

#1100 SOX-124 update texts
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/MergeRequestsTest.php
Labels: minor
