Repository keboola/storage-api-php-client, pull requests merged in 2023-10, with the labels that each got.

#1188 Ct 830 add parameter allow truncate if filter is empty
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: major

#1190 BIG-165 fix loading multiple tables when BQ IM using view
  tests/Backend/SOX/SOXWorkspaceTest.php
Labels: no release

#1194 CT-1128 add test for SNFLK exotic types import
  tests/Backend/Snowflake/ImportTypedTableTest.php
  tests/_data/exotic-types-snowflake.csv
Labels: no release

#1191 add ['allowTruncate' => true] to tests
  tests/Backend/CommonPart2/SlicedImportsTest.php
  tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
  tests/Backend/Redshift/CommonTest.php
  tests/Backend/Snowflake/TimestampTest.php
Labels: no release

#1189 testCreateTableInBucketWithDifferentBackendAsProjectDefault
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Labels: no release

#1198 BIG-173 add test for BQ partitioning
  apiary.apib
  tests/Backend/Bigquery/TableDefinitionOperationsPartitioningTest.php
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/CommonPart1/TimeTravelTest.php
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/SOX/PullTableTest.php
Labels: no release

#1201 Roman gcs gcp 360
  tests/File/AwsFileTest.php
  tests/File/AzureFileTest.php
  tests/File/GcsFileTest.php
Labels: no release

#1195 Ct 1138 dont create new brach every run
  tests/Backend/CommonPart1/BucketsTest.php
  tests/ClientProvider/TestSetupHelper.php
Labels: no release

#1204 Update to latest snflk driver
  Dockerfile
  docker/snowflake/generic.pol
Labels: no release

#1203 Big 183 ext table support
  docker-compose.yml
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/bootstrap.php
Labels: no release

#1206 update baseline
  phpstan-baseline.neon
Labels: no release

#1200 SOX-422 test that can create jobs can read configurations
  tests/Backend/SOX/SOXTokensTest.php
Labels: no release

#1205 SOX-397 SOX external buckets tests
  phpunit.xml.dist
  tests/Backend/ExternalBuckets/BaseExternalBuckets.php
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
  tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
  tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
Labels: no release

#1207 SOX-422 tokens with canCreateJobs can list components
  tests/Backend/SOX/SOXTokensTest.php
Labels: no release

#1210 Tune readme a bit, remove Travis badge and old changelog
  CHANGELOG.md
  README.md
Labels: docs, no release

#1209 Fix typos (Bigquery->BigQuery)
  apiary.apib
Labels: docs, no release

#1208 CT-1174 Fix tests around PK
  apiary.apib
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Synapse/CreateTableTest.php
Labels: no release

#1212 GCP-408 GCS reupload
  src/Keboola/StorageApi/GCSUploader.php
  tests/ClientTestCase.php
Labels: patch
