Repository keboola/storage-api-php-client, pull requests merged in 2024-09, with the labels that each got.

#1392 operator is optional an support only two options
  apiary.apib
  src/Keboola/StorageApi/Downloader/AbsUrlParser.php
  tests/Downloader/AbsUrlParserTest.php
Labels: no release

#1394 CT-1240 test bucket drop
  tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
Labels: no release

#1393 CT-1707 - /storage/jobs endpoint served from new StorageTable - tests
  apiary.apib
  tests/Common/JobsListTest.php
Labels: no release

#1395 FIX apiary doc
  apiary.apib
Labels: docs

#1352 CT-1445 GlobalSearch tests & docs
  .gitignore
  apiary.apib
  set-env.global-search-bq.template.sh
  set-env.global-search-mixed.template.sh
  set-env.global-search-sox.template.sh
  set-env.global-search.template.sh
  tests/Backend/CommonPart1/CreateTableTest.php
  tests/Backend/CommonPart1/DeleteTableTest.php
  tests/Backend/CommonPart1/TimeTravelTest.php
  tests/Backend/CommonPart2/SnapshottingTest.php
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Backend/SOX/MergeRequestsTest.php
  tests/Backend/SOX/PullTableTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Workspaces/WorkspacesUnloadTest.php
  tests/Common/BranchAwareClientTest.php
  tests/Common/BranchBucketsTest.php
  tests/Common/BranchComponentTest.php
  tests/Common/ComponentsTest.php
  tests/Common/GlobalSearchTest.php
Labels: no release

#1401 CT-1561 add option isSnowflakeSharedDatabase to register guide
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: minor

#1399 CT-1721 add network policies tests
  apiary.apib
  composer.json
  docker-compose.yml
  phpunit.xml.dist
  tests/Backend/NetworkPolicies/NetworkPoliciesTestCase.php
  tests/Backend/NetworkPolicies/SnowflakeNetworkPoliciesTest.php
  tests/Utils/ConnectionUtils.php
  tests/Utils/IpUtils.php
Labels: patch, no release

#1403 fix sox share test
  tests/Backend/SOX/ShareTest.php
  tests/Utils/SharingUtils.php
Labels: no release
