Repository keboola/storage-api-php-client, pull requests merged in 2024-04, with the labels that each got.

#1306 CT-1343 add TableDropTest
  tests/Common/TableDropTest.php
Labels: no release

#1312 CT-1356 docker compose
  .github/workflows/branch.yml
  .github/workflows/master.yml
  .github/workflows/tag.yml
  README.md
Labels: no release

#1310 CT-1348 test dataSizeBytes, rowsCount on empty table
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: no release

#1308 CT-1331 do not expect error when having no datatype anymore
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
  tests/Backend/Bigquery/TableExporterTest.php
  tests/Backend/Bigquery/TestExportDataProvidersTrait.php
Labels: no release

#1311 CT-745 file delete async
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/File/AwsFileTest.php
  tests/File/AzureFileTest.php
  tests/File/CommonFileTest.php
  tests/File/GcsFileTest.php
Labels: minor

#1313 now is able to register external bucket
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Labels: no release

#1316 CT-1118 testImportTreatValuesAsNull
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/ImportExportCommonTest.php
Labels: minor

#1318 BIG-246 test tableType for bigquery-external-table
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Labels: no release

#1263 CT-1238 fix expected order of keys
  tests/Backend/CommonPart1/BranchStorageTest.php
  tests/Common/DevBranchesTest.php
Labels: no release

#1317 CT-1340 table import ordered columns
  apiary.apib
  tests/Backend/CommonPart1/ImportExportCommonTest.php
  tests/_data/languages-without-headers-reordered-incremental.csv
  tests/_data/languages-without-headers-reordered-new-column.csv
  tests/_data/languages-without-headers-reordered.csv
Labels: minor

#1322 CT-1265 fix assert allow order change
  tests/Common/DevBranchesTest.php
Labels: no release

#1325 Note that PK columns cannot be nullable
  apiary.apib
Labels: docs
