Repository keboola/storage-api-php-client, pull requests merged in 2024-06, with the labels that each got.

#1344 CT-1440 add endpoint to client and apiary
  apiary.apib
  phpunit.xml.dist
  src/Keboola/StorageApi/Client.php
  tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
Labels: minor

#1345 CT-1439 refresh tables information test
  src/Keboola/StorageApi/Client.php
  tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
  tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
  tests/StorageApiTestCase.php
  tests/Utils/ConnectionUtils.php
Labels: no release

#1348 FIX client method for refresh-tables-information in bucket
  src/Keboola/StorageApi/Client.php
  tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
Labels: patch

#1349 FIX refresh-tables-information in bucket documentation
  apiary.apib
  phpstan-baseline.neon
  phpstan.neon
  src/Keboola/StorageApi/Client.php
Labels: patch

#1350 FIX refresh tables in bucket test
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/BranchStorageTest.php
  tests/Backend/CommonPart2/MetricsTest.php
  tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
  tests/Common/QueueJobsTest.php
  tests/Utils/EventTesterUtils.php
Labels: no release

#1351 CT-1486 chnage type to types and arr
  src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Labels: no release

#1353 CT-1434 add TypedTableWorkspacesLoadTest
  apiary.apib
  phpunit.xml.dist
  tests/Backend/Snowflake/TypedTableWorkspacesLoadTest.php
Labels: no release

#1357 remove `/`
  apiary.apib
Labels: no release

#1358 FIX token owner assertions
  tests/Common/TokensTest.php
Labels: no release

#1359 Drop bucket at the begining of the test
  tests/Common/TokensTest.php
Labels: no release

#1355 CT-1368 - add branch paramets
  src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Labels: no release

#1362 ct 1445 gs tests roman improve
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Common/BranchComponentTest.php
  tests/Common/ComponentsTest.php
Labels: no release

#1360 Add ws cleanup for bq tests
  tests/Backend/Bigquery/ImportTreatValuesAsNullTest.php
  tests/Backend/Bigquery/WorkspacesLoadTest.php
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: no release
