Repository keboola/storage-api-php-client, pull requests merged in 2024-02, with the labels that each got.

#1255 Add refresh for file
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/SOX/BranchFileStorageTest.php
  tests/File/GcsFileTest.php
Labels: minor

#1259 GMT-136 region in ws
  apiary.apib
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: patch

#1258 CT-1248
  tests/Backend/SOX/PullTableTest.php
Labels: no release

#1260 CT-1249 add BQ mixed test testLinkBucketExport
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Labels: no release

#1262 add @internal to uploader clases
  src/Keboola/StorageApi/ABSUploader.php
  src/Keboola/StorageApi/GCSUploader.php
  src/Keboola/StorageApi/S3Uploader.php
Labels: no release

#1265 CT-1229 buckets include params
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/BucketDetailOptions.php
  tests/Backend/CommonPart1/BucketsTest.php
Labels: minor

#1267 test project throw http ex in case of calling register guide with dif…
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1269 CT-1228 Events list make more clear how it works
  apiary.apib
Labels: no release

#1268 CT-1168 test managing triggers on tables in external buckets
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Labels: no release

#1270 CT-1264 Add tests for BQ
  tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
  tests/Backend/Workspaces/WorkspacesUnloadTest.php
Labels: no release

#1272 BIG-222 test if allowing delete ex bucket with deleted schema on backend
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
  tests/Backend/FileWorkspace/WorkspacesTest.php
Labels: no release

#1276 Hotifx: Remove double sprintf
  src/Keboola/StorageApi/GCSUploader.php
Labels: patch

#1275 CT-1282 Check that workspaces does not have create streamlit privilege
  tests/Backend/FileWorkspace/WorkspacesTest.php
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: no release

#1240 CT-1218 test orderBy with typed table
  apiary.apib
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Labels: major
