Repository keboola/storage-api-php-client, pull requests merged in 2024-05, with the labels that each got.

#1327 CT-1374-create-global-search-client-method
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Labels: no release

#1328 CT-1407 endpoint webalize column name
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Common/IndexTest.php
Labels: minor

#1329 add testCopyLoadOfTypedTable
  tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Labels: no release

#1330 CT-1425 test drpoing external buckets
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1320 Update apiary.apib
  apiary.apib
Labels: no release

#1334 PST-1006 Allow disabling retries on 503 Maintenance response
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/HandlerStack.php
  tests-unit/Client/MaintenanceTest.php
Labels: enhancement, minor

#1326 PST-1343 processorConfiguration,dataTypesConfiguration
  apiary.apib
  tests/Common/IndexTest.php
Labels: no release

#1332 test row deleted in devBranch shoudl be deleted in default after merge
  tests/Backend/SOX/MergeRequestsTest.php
Labels: no release

#1331 CT-1429 Request to webalize columns accepts an array as input
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Common/IndexTest.php
Labels: minor

#1338 CT-1425 test revoke
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1340 allow testcase
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release

#1339 CT-1447 test new grants
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1343 BIG-250 update BQ testPrimaryKeyOperationsOnTypedTable
  tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Labels: no release

#1342 CT-1449 add test to check if external bucket can be dropped without existing WS
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: no release

#1341 CT-1446 test eb on byodb
  docker-compose.yml
  phpunit.xml.dist
  tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
Labels: no release
