Repository keboola/storage-api-php-client, pull requests merged in 2025-07, with the labels that each got.

#1520 Update: DMD-195 - Reader WS reset public key
  tests/Backend/Snowflake/WorkspacesReaderTest.php
Labels: no release

#1521 CT-2185 test bq export filters
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Labels: no release

#1522 INC-24637 more tests for query endpoint
  tests/Backend/Snowflake/WorkspacesQueryTest.php
Labels: no release

#1526 chore(debian): Upgrade to Debian 11 (Bullseye)
  Dockerfile
Labels: enhancement, patch

#1529 feat: Make BackendConfiguration properties accessible from outside
  src/Keboola/StorageApi/Options/BackendConfiguration.php
Labels: patch

#1530 test(scheduled tasks): Move scheduled task test to correct suite
  phpunit.xml.dist
  tests/Backend/ExternalBuckets/ScheduledTasksTest.php
Labels: no release

#1524 Update: DMD-166 - Remove readers WS test
  phpunit.xml.dist
  tests/Backend/ReaderWorkspaces/WorkspacesReaderTest.php
Labels: no release

#1534 Test load to table with dynamic backend
  tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
Labels: no release
