Repository keboola/storage-api-php-client, pull requests merged in 2025-04, with the labels that each got.

#1482 remove deprecated tests
  src/Keboola/StorageApi/Client.php
  tests/Backend/Mixed/SharingTest.php
Labels: major

#1483 PAT-178 ws keypair
  apiary.apib
  composer.json
  src/Keboola/StorageApi/WorkspaceLoginType.php
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
  tests/Backend/WorkspaceConnectionTrait.php
  tests/Utils/CertificateSigningRequest.php
  tests/Utils/PemKeyCertificateGenerator.php
  tests/Utils/PemKeyCertificatePair.php
Labels: minor

#1486 DMD-92 Throw meaningful exception when view is out of sync
  tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Labels: no release

#1492 Roman/dmd 103 remove sync option for sharing
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/SharingTestWithTypedTables.php
  tests/Backend/Mixed/SharingToSpecificProjectsTest.php
  tests/Backend/Mixed/SharingToSpecificUsersTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
  tests/Backend/SOX/ShareTest.php
  tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
  tests/StorageApiTestCase.php
Labels: major
