Repository keboola/storage-api-php-client, pull requests merged in 2025-03, with the labels that each got.

#1463 DMD-64 remove depricated share method
  apiary.apib
  phpstan-baseline.neon
  tests/Backend/CommonPart1/TimeTravelTest.php
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
  tests/Backend/MixedSnowflakeExasol/SharingTest.php
  tests/Backend/MixedSnowflakeSynapse/SharingTest.php
  tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
  tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
  tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
Labels: major

#1468 Pepa types
  phpstan-baseline.neon
  src/Keboola/StorageApi/Options/BucketUpdateOptions.php
  src/Keboola/StorageApi/Options/Components/Configuration.php
  src/Keboola/StorageApi/Options/Components/ConfigurationMetadata.php
  src/Keboola/StorageApi/Options/Components/ConfigurationRow.php
  src/Keboola/StorageApi/Options/Components/ConfigurationRowState.php
  src/Keboola/StorageApi/Options/Components/ConfigurationState.php
  src/Keboola/StorageApi/Options/Components/ListComponentConfigurationsOptions.php
  src/Keboola/StorageApi/Options/Components/ListComponentsOptions.php
  src/Keboola/StorageApi/Options/Components/ListConfigurationMetadataOptions.php
  src/Keboola/StorageApi/Options/Components/ListConfigurationRowVersionsOptions.php
  src/Keboola/StorageApi/Options/Components/ListConfigurationRowsOptions.php
  src/Keboola/StorageApi/Options/Components/ListConfigurationVersionsOptions.php
  src/Keboola/StorageApi/Options/Components/ListConfigurationWorkspacesOptions.php
  src/Keboola/StorageApi/Options/Components/SearchComponentConfigurationsOptions.php
  src/Keboola/StorageApi/Options/FileUploadOptions.php
  src/Keboola/StorageApi/Options/FileUploadTransferOptions.php
  src/Keboola/StorageApi/Options/GetFileOptions.php
  src/Keboola/StorageApi/Options/IndexOptions.php
  src/Keboola/StorageApi/Options/ListFilesOptions.php
  src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php
  src/Keboola/StorageApi/Options/SearchTablesOptions.php
  src/Keboola/StorageApi/Options/StatsOptions.php
  src/Keboola/StorageApi/Options/TokenAbstractOptions.php
  src/Keboola/StorageApi/Options/TokenCreateOptions.php
Labels: patch

#1469 create config workspace wont reset password
  src/Keboola/StorageApi/Components.php
Labels: minor

#1470 Fix expected file sizes tests
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Labels: no release

#1471 fix jobs array pointer
  tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Labels: no release

#1472 CT-1415 test that UUID is present in all events
  tests/Common/EventsTest.php
  tests/Common/TableEventsTest.php
  tests/Utils/EventTesterUtils.php
Labels: no release

#1473 CT-1415 test that event cen be retrieve by uuid
  apiary.apib
  tests/Common/EventsTest.php
Labels: no release

#1475 fix unstable global search assertions
  src/Keboola/StorageApi/Client.php
  tests/Backend/Snowflake/TableDefinitionOperationsTest.php
  tests/Backend/Workspaces/WorkspacesUnloadTest.php
  tests/StorageApiTestCase.php
  tests/Utils/GlobalSearchTesterUtils.php
Labels: no release

#1477 fix array reindex after filter
  tests/Utils/GlobalSearchTesterUtils.php
Labels: no release

#1474 CT-1974 Remove support for `valuesByTableInStorage` option.
  apiary.apib
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release

#1476 CT-2065 allow use UUID only
  apiary.apib
  tests/Common/BranchEventsTest.php
  tests/Common/EventsTest.php
  tests/Common/TableEventsTest.php
  tests/Utils/EventTesterUtils.php
Labels: no release

#1480 update GS test asserts
  tests/Common/BranchBucketsTest.php
  tests/Utils/GlobalSearchTesterUtils.php
Labels: no release

#1481 Enable tests for BQ
  apiary.apib
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release
