Repository keboola/storage-api-php-client, pull requests merged in 2025-01, with the labels that each got.

#1436 deps: allow symfony 7
  composer.json
Labels: patch

#1437 CT-1920 new Workspace props
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
  tests/Backend/WorkspaceCredentialsAssertTrait.php
  tests/Backend/Workspaces/ComponentsWorkspacesTest.php
  tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: minor

#1440 CT-1951 test of new params valuesBy*
  apiary.apib
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release

#1439 DMD-33 - SDS bucket refresh test update
  tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Labels: no release

#1441 CT-1952 test delete rows by workspace
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release

#1444 stabilize delete rows tests
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release

#1438 CT-1921 Workspace login name
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Snowflake/WorkspacesLoginNameTest.php
  tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
  tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
Labels: minor

#1442 CT-1926 SSO parameter for workspace detail
  apiary.apib
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: no release

#1445 CT-1952 test invalid WS
  tests/Backend/CommonPart1/DeleteRowsTest.php
Labels: no release
