Repository keboola/storage-api-php-client, pull requests merged in 2025-02, with the labels that each got.

#1443 DMD-53 Bucket color test
  apiary.apib
  phpstan-baseline.neon
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Options/BucketUpdateOptions.php
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/Mixed/SharingTest.php
Labels: patch

#1447 DMD-53 fix expected exception message in text
  tests/Backend/CommonPart1/BucketsTest.php
Labels: no release

#1448 DMD-69 - bucket owner email test
  apiary.apib
  tests/Backend/CommonPart1/BucketsTest.php
  tests/Backend/Mixed/SharingTest.php
Labels: no release

#1449 CT-1783 Remove TWC tests
  phpunit.xml.dist
  tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
  tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
  tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
  tests/Backend/TableWithConfigurationUtils.php
Labels: no release

#1450 DMD-77 test shared bucket list fields color and owner
  apiary.apib
  tests/Backend/Mixed/SharingTest.php
Labels: no release

#1452 CT-1594 - adjust error message
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
  tests/Backend/SOX/ShareTest.php
Labels: no release

#1451 CT-2000 new export option includeInternalTimestamp
  apiary.apib
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/TableExporter.php
  tests/Backend/CommonPart1/ExportParamsTest.php
Labels: minor

#1453 CT-1999 import timestamp
  apiary.apib
  src/Keboola/StorageApi/Client.php
  tests/Backend/CommonPart1/ImportExportCommonTest.php
  tests/_data/languages.with-timestamp.csv
  tests/_data/languages.with-timestamp.no-header.csv
Labels: minor

#1455 DMD-67 - update tests for external buckets in import mapping
  tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
  tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Labels: minor

#1456 CT-1979 person sso login type for workspace
  apiary.apib
  src/Keboola/StorageApi/WorkspaceLoginType.php
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
  tests/Backend/Workspaces/WorkspacesTest.php
Labels: minor

#1459 fix: Make arguments with default `null` nullable explicitly
  src/Keboola/StorageApi/Client.php
  src/Keboola/StorageApi/Components.php
  src/Keboola/StorageApi/Downloader/GcsClientFactory.php
  src/Keboola/StorageApi/GCSUploader.php
  src/Keboola/StorageApi/HandlerStack.php
  src/Keboola/StorageApi/S3Uploader.php
  tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
  tests/StorageApiTestCase.php
  tests/Utils/EventTesterUtils.php
Labels: patch

#1464 Roman fix share bucket
  phpstan-baseline.neon
  tests/Backend/Mixed/SharingTest.php
  tests/Backend/Mixed/StorageApiSharingTestCase.php
  tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Labels: no release

#1462 CT-2016 New Workspaces::executeQuery
  apiary.apib
  src/Keboola/StorageApi/Workspaces.php
  tests/Backend/Bigquery/WorkspacesQueryTest.php
  tests/Backend/Snowflake/WorkspacesQueryTest.php
Labels: minor
